const {chromium}=require(process.env.SLIDES_PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({args:['--enable-unsafe-swiftshader'],...(process.env.SLIDES_BROWSER?{executablePath:process.env.SLIDES_BROWSER}:{})});try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const url=process.argv[2],sourcePath=process.argv[3];await page.goto(url+'#opening',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.SlidesMotion&&window.SlidesDiagramMotion);assert.equal(await page.locator('.diagram-error').count(),0);assert.equal(await page.locator('.slides-diagram-morph').count(),3);
 await page.keyboard.press('m');await page.waitForFunction(()=>document.querySelector('[data-motion-status]').textContent.includes('Edits can be saved'));
 const duration=page.locator('[data-motion-duration]');await duration.fill('1100');await duration.dispatchEvent('change');await page.locator('[data-motion-undo]').click();assert.equal(await duration.inputValue(),'800');await page.locator('[data-motion-redo]').click();assert.equal(await duration.inputValue(),'1100');
 await page.locator('[data-motion-replay-mode]').selectOption('once');const bar=page.locator('.slides-motion-bar').first(),box=await bar.boundingBox();await page.mouse.move(box.x+5,box.y+12);await page.mouse.down();await page.mouse.move(box.x+70,box.y+12,{steps:6});await page.mouse.up();assert.ok(Number(await page.locator('[data-motion-delay]').inputValue())>50);
 if(sourcePath){await Promise.all([page.waitForEvent('domcontentloaded'),page.locator('[data-motion-save]').click()]);await page.waitForFunction(()=>window.SlidesMotion);const source=fs.readFileSync(sourcePath,'utf8');assert.ok(source.includes('duration="1100"')&&source.includes('replay="once"'));await page.keyboard.press('m');await page.waitForFunction(()=>document.querySelector('[data-motion-status]').textContent.includes('Edits can be saved'));await duration.fill('1200');await duration.dispatchEvent('change');fs.appendFileSync(sourcePath,'\n<!-- external edit -->\n');await page.locator('[data-motion-save]').click();await page.waitForFunction(()=>document.querySelector('[data-motion-status]').textContent.includes('changed'));assert.ok(!fs.readFileSync(sourcePath,'utf8').includes('duration="1200"'));}
 await page.keyboard.press('Escape');await page.evaluate(()=>SlidesNav.show(1,0,true));const shape=page.locator('.deck-active .slides-diagram-morph figure:visible [data-morph-id="adoption"] rect');const before=Number(await shape.getAttribute('width'));await page.evaluate(()=>{SlidesNav.next();SlidesMotion.pause();SlidesMotion.seek(500)});const middle=Number(await shape.getAttribute('width'));await page.evaluate(()=>SlidesMotion.seek(1000));const after=Number(await shape.getAttribute('width'));assert.ok(before<middle&&middle<after,JSON.stringify({before,middle,after}));await page.evaluate(()=>SlidesMotion.reverse());await page.waitForTimeout(100);await page.evaluate(()=>SlidesMotion.pause());assert.ok(Number(await shape.getAttribute('width'))<after);await page.evaluate(()=>{SlidesNav.prev();SlidesMotion.seek(1000)});assert.equal(Number(await shape.getAttribute('width')),before);
 await page.evaluate(()=>{document.querySelector('.deck-active .slides-diagram-morph').dataset.diagramDuration='0';SlidesNav.next()});assert.equal(await page.evaluate(()=>SlidesDiagramMotion.duration()),0);assert.equal(Number(await shape.getAttribute('width')),after);await page.evaluate(()=>{document.querySelector('.deck-active .slides-diagram-morph').dataset.diagramDuration='1000';SlidesNav.prev();SlidesNav.next();SlidesMotion.pause();SlidesMotion.seek(500);SlidesNav.show(0,0,true);SlidesNav.show(1,1,true)});assert.equal(Number(await shape.getAttribute('width')),after,'revisiting an anchor must settle its exact pose');
 await page.evaluate(()=>SlidesNav.show(2,0,true));const old=await page.locator('.deck-active figure:visible [data-morph-id="api"] rect').getAttribute('x');await page.evaluate(()=>{SlidesNav.next();SlidesMotion.seek(1000)});assert.equal(await page.locator('.deck-active figure:visible [data-morph-id="api"] rect').getAttribute('x'),old);
 await page.evaluate(()=>SlidesNav.show(6,0,true));await page.waitForFunction(()=>document.querySelector('.deck-active .slide-graphic')?.dataset.gosxScene3dReady==='true');await page.waitForFunction(()=>document.querySelector('.deck-active .slide-graphic')?.dataset.appliedStep==='0');await page.evaluate(()=>SlidesNav.next());await page.waitForFunction(()=>document.querySelector('.deck-active .slide-graphic')?.dataset.appliedStep==='1');assert.deepEqual(errors,[]);
 if(process.env.SLIDES_SCREENSHOT_DIR){fs.mkdirSync(process.env.SLIDES_SCREENSHOT_DIR,{recursive:true});for(const [slide,name]of [[0,'motion-studio'],[1,'growth'],[4,'radar'],[5,'sankey'],[6,'native-scatter']]){await page.evaluate(n=>SlidesNav.show(n,0,true),slide);if(slide===0)await page.keyboard.press('m');await page.waitForTimeout(350);await page.screenshot({path:process.env.SLIDES_SCREENSHOT_DIR+'/'+name+'.png'});if(slide===0)await page.keyboard.press('Escape');}await page.setViewportSize({width:390,height:844});await page.evaluate(()=>SlidesNav.show(0,0,true));await page.keyboard.press('m');assert.ok(await page.locator('dialog:visible').count());assert.equal(await page.evaluate(()=>document.querySelector('dialog[open]').scrollWidth<=document.querySelector('dialog[open]').clientWidth),true);await page.screenshot({path:process.env.SLIDES_SCREENSHOT_DIR+'/motion-mobile.png'});}
 console.log('PASS persistent motion editing, conflict guard, SVG seek/reverse/backward poses, stable actors, native scatter tours');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
